### ISSUE TITLE
What lib for XDCC?

### ISSUE THREAD

**Issue by xetra11** [JanGe/xdcc#10]
Hey there!

I'd like to write my own XDCC leecher with Haskell or Rust.
Just wanted to know what library you used since I do not have a single idea of haskells library ecosystem

**Comment by JanGe** [comment]
I'm using [`irc-client`](https://www.stackage.org/lts/package/irc-client) for connection handling and message parsing and my own [`irc-dcc`](https://www.stackage.org/lts/package/irc-dcc) library for DCC command parsing/encoding and DCC file transfers.

You can find a complete list of libraries used in the `build-depends` section of the [cabal file](https://github.com/JanGe/xdcc/blob/master/xdcc.cabal).

XDCC commands are just normal text messages sent to other users to initiate DCC file transfers. I'm only using [two XDCC commands](https://github.com/JanGe/xdcc/blob/df1db807f47ce40ccce9c1ded43c6bd4a6f7628f/src/XDCC.hs#L31) (`XDCC SEND` and `XDCC CANCEL`) so I didn't see a need to move them to their own library so far.

**Comment by xetra11** [comment]
thank you for the infos!

**Comment by JanGe** [comment]
You're welcome :)
